<?php
/**
 * @file
 * ia_theme_information.features.field_instance.inc
 */

/**
 * Implements hook_field_default_field_instances().
 */
function ia_theme_information_field_default_field_instances() {
  $field_instances = array();

  // Exported field_instance: 'bean-ia_theme_information-field_content_examples'
  $field_instances['bean-ia_theme_information-field_content_examples'] = array(
    'bundle' => 'ia_theme_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 2,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_content_examples',
    'label' => 'Content Examples',
    'required' => 0,
    'settings' => array(
      'text_processing' => 0,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'size' => 60,
      ),
      'type' => 'text_textfield',
      'weight' => 13,
    ),
  );

  // Exported field_instance: 'bean-ia_theme_information-field_region_description'
  $field_instances['bean-ia_theme_information-field_region_description'] = array(
    'bundle' => 'ia_theme_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'above',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 0,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_region_description',
    'label' => 'Region Description',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 11,
    ),
  );

  // Exported field_instance: 'bean-ia_theme_information-field_technical_information'
  $field_instances['bean-ia_theme_information-field_technical_information'] = array(
    'bundle' => 'ia_theme_information',
    'default_value' => NULL,
    'deleted' => 0,
    'description' => '',
    'display' => array(
      'default' => array(
        'label' => 'inline',
        'module' => 'text',
        'settings' => array(),
        'type' => 'text_default',
        'weight' => 1,
      ),
    ),
    'entity_type' => 'bean',
    'field_name' => 'field_technical_information',
    'label' => 'Technical Information',
    'required' => 0,
    'settings' => array(
      'text_processing' => 1,
      'user_register_form' => FALSE,
    ),
    'widget' => array(
      'active' => 1,
      'module' => 'text',
      'settings' => array(
        'rows' => 5,
      ),
      'type' => 'text_textarea',
      'weight' => 12,
    ),
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('Content Examples');
  t('Region Description');
  t('Technical Information');

  return $field_instances;
}
